# Generated by Django 4.1 on 2023-12-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.DateField(blank=True, null=True)),
                ('entregado', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellidos', models.CharField(max_length=40, null=True)),
                ('calle', models.CharField(max_length=40, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('codigopostal', models.IntegerField(null=True)),
                ('ciudad', models.CharField(max_length=40, null=True)),
                ('tarjeta', models.CharField(blank=True, max_length=16, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('fechacad', models.CharField(blank=True, max_length=5, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
